[package]
name = "polyorama-ui-egui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
egui.workspace = true
egui-wgpu.workspace = true
wgpu.workspace = true
polyorama-core = { path = "../polyorama-core" }
polyorama-render-wgpu = { path = "../polyorama-render-wgpu" }
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
