// @generated by `cargo xtask tokens generate` from design/tokens/polyorama.tokens.json.
// Do not edit by hand. This file is compiled directly; runtime JSON parsing is forbidden.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Rgba8 {
    pub red: u8,
    pub green: u8,
    pub blue: u8,
    pub alpha: u8,
}

impl From<Rgba8> for egui::Color32 {
    fn from(value: Rgba8) -> Self {
        Self::from_rgba_unmultiplied(value.red, value.green, value.blue, value.alpha)
    }
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Points(pub f32);

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Ratio(pub f32);

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct FontWeight(pub u16);

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Milliseconds(pub u32);

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ThemeVariant {
    Light,
    Dark,
    LightHighContrast,
    DarkHighContrast,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DensityVariant {
    Compact,
    Comfortable,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ColourTokens {
    pub surface_canvas: Rgba8,
    pub surface_panel: Rgba8,
    pub surface_raised: Rgba8,
    pub border_subtle: Rgba8,
    pub text_primary: Rgba8,
    pub text_muted: Rgba8,
    pub accent_primary: Rgba8,
    pub accent_on_accent: Rgba8,
    pub selection_background: Rgba8,
    pub focus_ring: Rgba8,
    pub overlay_annotation: Rgba8,
    pub overlay_selected: Rgba8,
    pub overlay_vertex: Rgba8,
    pub overlay_footprint: Rgba8,
    pub status_success: Rgba8,
    pub status_warning: Rgba8,
    pub status_error: Rgba8,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct SpacingTokens {
    pub unit: Points,
    pub inline: Points,
    pub block: Points,
    pub section: Points,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct GeometryTokens {
    pub application_bar_height: Points,
    pub control_height: Points,
    pub control_padding_x: Points,
    pub control_padding_y: Points,
    pub control_radius: Points,
    pub minimum_hit_size: Points,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct TypographyTokens {
    pub body_size: Points,
    pub body_weight: FontWeight,
    pub label_size: Points,
    pub label_weight: FontWeight,
    pub line_height: Ratio,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct MotionTokens {
    pub quick: Milliseconds,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct DesignTokens {
    pub colours: ColourTokens,
    pub spacing: SpacingTokens,
    pub geometry: GeometryTokens,
    pub typography: TypographyTokens,
    pub motion: MotionTokens,
}

impl DesignTokens {
    pub const fn resolve(theme: ThemeVariant, density: DensityVariant) -> Self {
        let colours = match theme {
            ThemeVariant::Light => COLOURS_LIGHT,
            ThemeVariant::Dark => COLOURS_DARK,
            ThemeVariant::LightHighContrast => COLOURS_LIGHT_HIGH_CONTRAST,
            ThemeVariant::DarkHighContrast => COLOURS_DARK_HIGH_CONTRAST,
        };
        let (spacing, geometry) = match density {
            DensityVariant::Compact => (SPACING_COMPACT, GEOMETRY_COMPACT),
            DensityVariant::Comfortable => (SPACING_COMFORTABLE, GEOMETRY_COMFORTABLE),
        };
        Self {
            colours,
            spacing,
            geometry,
            typography: TYPOGRAPHY,
            motion: MOTION,
        }
    }
}

const COLOURS_LIGHT: ColourTokens = ColourTokens {
    surface_canvas: Rgba8 {
        red: 243,
        green: 245,
        blue: 246,
        alpha: 255,
    },
    surface_panel: Rgba8 {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
    },
    surface_raised: Rgba8 {
        red: 231,
        green: 236,
        blue: 239,
        alpha: 255,
    },
    border_subtle: Rgba8 {
        red: 137,
        green: 150,
        blue: 159,
        alpha: 255,
    },
    text_primary: Rgba8 {
        red: 23,
        green: 32,
        blue: 39,
        alpha: 255,
    },
    text_muted: Rgba8 {
        red: 83,
        green: 97,
        blue: 106,
        alpha: 255,
    },
    accent_primary: Rgba8 {
        red: 8,
        green: 119,
        blue: 129,
        alpha: 255,
    },
    accent_on_accent: Rgba8 {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
    },
    selection_background: Rgba8 {
        red: 199,
        green: 236,
        blue: 235,
        alpha: 255,
    },
    focus_ring: Rgba8 {
        red: 0,
        green: 111,
        blue: 120,
        alpha: 255,
    },
    overlay_annotation: Rgba8 {
        red: 105,
        green: 227,
        blue: 210,
        alpha: 255,
    },
    overlay_selected: Rgba8 {
        red: 255,
        green: 196,
        blue: 74,
        alpha: 255,
    },
    overlay_vertex: Rgba8 {
        red: 240,
        green: 244,
        blue: 238,
        alpha: 255,
    },
    overlay_footprint: Rgba8 {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
    },
    status_success: Rgba8 {
        red: 25,
        green: 115,
        blue: 76,
        alpha: 255,
    },
    status_warning: Rgba8 {
        red: 134,
        green: 95,
        blue: 0,
        alpha: 255,
    },
    status_error: Rgba8 {
        red: 165,
        green: 45,
        blue: 50,
        alpha: 255,
    },
};

const COLOURS_DARK: ColourTokens = ColourTokens {
    surface_canvas: Rgba8 {
        red: 11,
        green: 15,
        blue: 18,
        alpha: 255,
    },
    surface_panel: Rgba8 {
        red: 19,
        green: 24,
        blue: 29,
        alpha: 255,
    },
    surface_raised: Rgba8 {
        red: 27,
        green: 34,
        blue: 41,
        alpha: 255,
    },
    border_subtle: Rgba8 {
        red: 69,
        green: 83,
        blue: 94,
        alpha: 255,
    },
    text_primary: Rgba8 {
        red: 231,
        green: 237,
        blue: 242,
        alpha: 255,
    },
    text_muted: Rgba8 {
        red: 157,
        green: 170,
        blue: 179,
        alpha: 255,
    },
    accent_primary: Rgba8 {
        red: 43,
        green: 171,
        blue: 181,
        alpha: 255,
    },
    accent_on_accent: Rgba8 {
        red: 6,
        green: 16,
        blue: 18,
        alpha: 255,
    },
    selection_background: Rgba8 {
        red: 22,
        green: 77,
        blue: 82,
        alpha: 255,
    },
    focus_ring: Rgba8 {
        red: 112,
        green: 222,
        blue: 210,
        alpha: 255,
    },
    overlay_annotation: Rgba8 {
        red: 105,
        green: 227,
        blue: 210,
        alpha: 255,
    },
    overlay_selected: Rgba8 {
        red: 255,
        green: 196,
        blue: 74,
        alpha: 255,
    },
    overlay_vertex: Rgba8 {
        red: 240,
        green: 244,
        blue: 238,
        alpha: 255,
    },
    overlay_footprint: Rgba8 {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
    },
    status_success: Rgba8 {
        red: 99,
        green: 196,
        blue: 154,
        alpha: 255,
    },
    status_warning: Rgba8 {
        red: 225,
        green: 183,
        blue: 90,
        alpha: 255,
    },
    status_error: Rgba8 {
        red: 239,
        green: 129,
        blue: 125,
        alpha: 255,
    },
};

const COLOURS_LIGHT_HIGH_CONTRAST: ColourTokens = ColourTokens {
    surface_canvas: Rgba8 {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
    },
    surface_panel: Rgba8 {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
    },
    surface_raised: Rgba8 {
        red: 237,
        green: 241,
        blue: 243,
        alpha: 255,
    },
    border_subtle: Rgba8 {
        red: 38,
        green: 50,
        blue: 56,
        alpha: 255,
    },
    text_primary: Rgba8 {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 255,
    },
    text_muted: Rgba8 {
        red: 48,
        green: 59,
        blue: 66,
        alpha: 255,
    },
    accent_primary: Rgba8 {
        red: 0,
        green: 92,
        blue: 98,
        alpha: 255,
    },
    accent_on_accent: Rgba8 {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
    },
    selection_background: Rgba8 {
        red: 196,
        green: 245,
        blue: 241,
        alpha: 255,
    },
    focus_ring: Rgba8 {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 255,
    },
    overlay_annotation: Rgba8 {
        red: 105,
        green: 227,
        blue: 210,
        alpha: 255,
    },
    overlay_selected: Rgba8 {
        red: 255,
        green: 196,
        blue: 74,
        alpha: 255,
    },
    overlay_vertex: Rgba8 {
        red: 240,
        green: 244,
        blue: 238,
        alpha: 255,
    },
    overlay_footprint: Rgba8 {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
    },
    status_success: Rgba8 {
        red: 7,
        green: 95,
        blue: 59,
        alpha: 255,
    },
    status_warning: Rgba8 {
        red: 104,
        green: 73,
        blue: 0,
        alpha: 255,
    },
    status_error: Rgba8 {
        red: 134,
        green: 32,
        blue: 39,
        alpha: 255,
    },
};

const COLOURS_DARK_HIGH_CONTRAST: ColourTokens = ColourTokens {
    surface_canvas: Rgba8 {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 255,
    },
    surface_panel: Rgba8 {
        red: 9,
        green: 13,
        blue: 15,
        alpha: 255,
    },
    surface_raised: Rgba8 {
        red: 17,
        green: 25,
        blue: 29,
        alpha: 255,
    },
    border_subtle: Rgba8 {
        red: 183,
        green: 197,
        blue: 206,
        alpha: 255,
    },
    text_primary: Rgba8 {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
    },
    text_muted: Rgba8 {
        red: 213,
        green: 221,
        blue: 226,
        alpha: 255,
    },
    accent_primary: Rgba8 {
        red: 113,
        green: 255,
        blue: 245,
        alpha: 255,
    },
    accent_on_accent: Rgba8 {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 255,
    },
    selection_background: Rgba8 {
        red: 6,
        green: 63,
        blue: 66,
        alpha: 255,
    },
    focus_ring: Rgba8 {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
    },
    overlay_annotation: Rgba8 {
        red: 105,
        green: 227,
        blue: 210,
        alpha: 255,
    },
    overlay_selected: Rgba8 {
        red: 255,
        green: 196,
        blue: 74,
        alpha: 255,
    },
    overlay_vertex: Rgba8 {
        red: 240,
        green: 244,
        blue: 238,
        alpha: 255,
    },
    overlay_footprint: Rgba8 {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
    },
    status_success: Rgba8 {
        red: 143,
        green: 255,
        blue: 200,
        alpha: 255,
    },
    status_warning: Rgba8 {
        red: 255,
        green: 225,
        blue: 138,
        alpha: 255,
    },
    status_error: Rgba8 {
        red: 255,
        green: 170,
        blue: 166,
        alpha: 255,
    },
};

const SPACING_COMPACT: SpacingTokens = SpacingTokens {
    unit: Points(4.0),
    inline: Points(5.0),
    block: Points(3.0),
    section: Points(8.0),
};

const GEOMETRY_COMPACT: GeometryTokens = GeometryTokens {
    application_bar_height: Points(32.0),
    control_height: Points(24.0),
    control_padding_x: Points(7.0),
    control_padding_y: Points(3.0),
    control_radius: Points(3.0),
    minimum_hit_size: Points(32.0),
};

const SPACING_COMFORTABLE: SpacingTokens = SpacingTokens {
    unit: Points(4.0),
    inline: Points(7.0),
    block: Points(5.0),
    section: Points(12.0),
};

const GEOMETRY_COMFORTABLE: GeometryTokens = GeometryTokens {
    application_bar_height: Points(38.0),
    control_height: Points(28.0),
    control_padding_x: Points(9.0),
    control_padding_y: Points(4.0),
    control_radius: Points(3.0),
    minimum_hit_size: Points(32.0),
};

const TYPOGRAPHY: TypographyTokens = TypographyTokens {
    body_size: Points(13.0),
    body_weight: FontWeight(400),
    label_size: Points(12.5),
    label_weight: FontWeight(600),
    line_height: Ratio(1.35),
};

const MOTION: MotionTokens = MotionTokens {
    quick: Milliseconds(120),
};
