[package]
name = "polyorama-render-wgpu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bytemuck.workspace = true
parking_lot.workspace = true
tracing.workspace = true
web-time.workspace = true
wgpu.workspace = true
polyorama-core = { path = "../polyorama-core" }
polyorama-runtime = { path = "../polyorama-runtime" }
