#!/usr/bin/env python3
"""Compile Polyorama's closed SVG subset into dependency-free vector geometry."""
import argparse
from pathlib import Path
import re
import subprocess
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'crates/polyorama-ui-egui/assets/icons'
OUTPUT = ROOT / 'crates/polyorama-ui-egui/src/generated_icons.rs'
NS = '{http://www.w3.org/2000/svg}'


def number(value):
    result = float(value)
    if not 0 <= result <= 24:
        raise ValueError(f'coordinate outside icon grid: {value}')
    return repr(result)


def compile_svg(path):
    svg = ET.fromstring(path.read_text())
    expected = {'viewBox': '0 0 24 24', 'fill': 'none', 'stroke': 'currentColor',
                'stroke-width': '2', 'stroke-linecap': 'round', 'stroke-linejoin': 'round'}
    if svg.tag != NS + 'svg' or svg.attrib != expected:
        raise ValueError(f'{path}: unsupported icon style')
    geometry = []
    for shape in svg:
        if shape.tag == NS + 'path' and set(shape.attrib) == {'d'}:
            # Absolute M/L/Z only, with explicit command letters and whitespace.
            words = shape.attrib['d'].split()
            points = []
            closed = False
            def emit():
                if len(points) < 2:
                    raise ValueError(f'{path}: path needs at least two points')
                coords = ', '.join(f'[{x}, {y}]' for x, y in points)
                geometry.append(f'IconGeometry::Path(&[{coords}], {str(closed).lower()})')
            while words:
                command = words.pop(0)
                if command == 'M':
                    if points:
                        emit()
                    points, closed = [], False
                elif command == 'Z':
                    closed = True
                    emit()
                    points, closed = [], False
                    continue
                elif command != 'L' or not points:
                    raise ValueError(f'{path}: unsupported path command {command}')
                points.append((number(words.pop(0)), number(words.pop(0))))
            if points:
                emit()
        elif shape.tag == NS + 'circle':
            filled = shape.attrib.get('fill') == 'currentColor'
            expected_keys = {'cx', 'cy', 'r'} | ({'fill', 'stroke'} if filled else set())
            if set(shape.attrib) != expected_keys or (filled and shape.attrib['stroke'] != 'none'):
                raise ValueError(f'{path}: unsupported circle')
            x, y, radius = [number(shape.attrib[key]) for key in ('cx', 'cy', 'r')]
            geometry.append(f'IconGeometry::Circle([{x}, {y}], {radius}, {str(filled).lower()})')
        else:
            raise ValueError(f'{path}: unsupported SVG element')
    if not geometry:
        raise ValueError(f'{path}: empty artwork')
    return geometry


def generate(source=SOURCE):
    paths = sorted(source.glob('*.svg'))
    variants = []
    for path in paths:
        if not re.fullmatch('[a-z]+(-[a-z]+)*', path.stem):
            raise ValueError(f'invalid icon filename: {path}')
        variants.append((''.join(word.title() for word in path.stem.split('-')), compile_svg(path)))
    lines = ['// @generated by python3 tools/generate-icons.py; do not edit.',
             '/// Bounded, project-authored artwork. Icons never supply action names.',
             '#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]',
             '#[non_exhaustive]', 'pub enum IconId {']
    lines += [f'    {name},' for name, _ in variants]
    lines += ['}', 'impl IconId {', '    /// Complete initial vocabulary in a stable display order.',
              '    pub const ALL: &\'static [Self] = &[']
    lines += [f'        Self::{name},' for name, _ in variants]
    lines += ['    ];', '    fn geometry(self) -> &\'static [IconGeometry] {', '        match self {']
    lines += [f'            Self::{name} => &[{", ".join(shapes)}],' for name, shapes in variants]
    lines += ['        }', '    }', '}']
    result = subprocess.run(['rustfmt', '--edition', '2024'], input='\n'.join(lines)+'\n',
                            text=True, capture_output=True, check=True)
    return result.stdout


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if OUTPUT.read_text() != generated:
            raise SystemExit('icon geometry drift; run python3 tools/generate-icons.py')
    else:
        OUTPUT.write_text(generated)
